- name:           "Kill unnecessary services"
  service:
    name:         postfix
    state:        stopped
    enabled:      no
  ignore_errors:  true

- name:           "Remove extraneous packages"
  yum:
    name:
      - ed
      - ftp
      - nano
      - rsync
      - screen
      - tmux
      - vim
      - wget
      - postfix
    state:        absent
    update_cache: yes
