- name:          "reboot_now"
  command:       "sleep 2 & shutdown -r now"
  async:         1
  poll:          0
  ignore_errors: true

- name:          "await_restart"
  wait_for:
    host:        "{{ inventory_hostname }}"
    state:       started
    delay:       15
    timeout:     30
