- name:          "Base setup"
  hosts:         all
  become:        yes
  become_method: sudo
  roles:
    - base_setup

- name:          "Harden"
  hosts:         all
  become:        yes
  become_method: sudo
  roles:
    - package_removal
#    - user_management
