- name:               "Create provisioner group"
  group:
    name:             provisioner
    state:            present
    gid:              1401

- name:               "Create provisioner user"
  user:
    name:             provisioner
    comment:          Provisioner System User
    state:            present
    shell:            /bin/bash
    group:            provisioner
    generate_ssh_key: yes
    ssh_key_bits:     2048
    ssh_key_comment:  provisioner@{{ inventory_hostname }}
    uid:              1401
    system:           true
  register:           provisioner_user

- name:               "Get the Provisioner user's public key"
  shell:              echo {{ item }} > {{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic_short }}_provisioner_id_rsa.pub
  with_items:
    - "{{ provisioner_user.ssh_public_key }}"
  delegate_to:        localhost
  become:             no

- name:               "Grant passwordless sudo rights to provisioner group"
  lineinfile:
    path:             /etc/sudoers.d/provisioner
    regexp:           '^%provisioner'
    line:             '%provisioner ALL=(ALL) NOPASSWD: ALL'
    state:            present
    create:           yes

- name:               "Deactivate root login shell"
  user:
    name:             root
    state:            present
    shell:            /sbin/nologin

- name:               "Remove postfix user"
  user:
    name:             postfix
    state:            absent

- name:               "Disable Ctrl + Alt + Del"
  shell:              |
    systemctl mask ctrl-alt-del.target
    systemctl daemon-reload

- name:               "Disable root login (sshd config)"
  replace:
    path:             /etc/ssh/sshd_config
    regexp:           '#PermitRootLogin yes'
    replace:          'PermitRootLogin no'

- name:               "Ensure Public Key Authentication"
  replace:
    path:             /etc/ssh/sshd_config
    regexp:           '#PubkeyAuthentication yes'
    replace:          'PubkeyAuthentication yes'

- name:               "Disable X11 forwarding"
  replace:
    path:             /etc/ssh/sshd_config
    regexp:           'X11Forwarding yes'
    replace:          'X11Forwarding no'

- name:               "Enable port forwarding"
  replace:
    path:             /etc/ssh/sshd_config
    regexp:           '#GatewayPorts no'
    replace:          'GatewayPorts yes'

- name:               "Setup Restricted BASH"
  file:
    src:              /bin/bash
    dest:             /bin/rbash
    state:            link

- name:               "Activate Restricted BASH"
  replace:
    path:             /etc/passwd
    regexp:           '\/bin\/bash$'
    replace:          '/bin/rbash'

- name:               "Remove sudo from wheel group (1/2)"
  lineinfile:
    path:             /etc/sudoers
    regexp:           "^%wheel"
    state:            absent

- name:               "Remove sudo from wheel group (2/2)"
  lineinfile:
    path:             /etc/sudoers
    regexp:           "^#\ %wheel"
    state:            absent

- name:               "Restart SSH"
  service:
    name:             sshd
    state:            restarted
    enabled:          yes
  notify:
    - reboot_now
    - await_restart
